// ============================================================
//  N&N CLOTHIFY — Homepage Banner Data
//
//  This file drives the carousel banner on the homepage.
//  DO NOT edit this file by hand — use admin.html → Banners tab
//  to manage banners, then click "Export & Download" to get this
//  file, and commit it to GitHub.
//
//  image    → full-width banner photo (Cloudinary upload or any URL).
//             Leave blank to show a styled text/gradient banner instead.
//  ctaType  → "category" | "new" | "all" | "url"
//  ctaValue → category id (for "category"), or the link (for "url")
// ============================================================

const BANNERS_DATA = [
  {
    id: "demo_banner_1",
    image: "",
    tag: "Just Dropped",
    title: "New Dress Collection",
    subtitle: "Fresh western & ethnic dresses, made for every mood.",
    ctaText: "Shop Dresses",
    ctaType: "category",
    ctaValue: "western",
    isDemo: true
  },
  {
    id: "demo_banner_2",
    image: "",
    tag: "Limited Time",
    title: "Festive Season Event",
    subtitle: "Big discounts on sarees & kurtis for the celebration season.",
    ctaText: "Explore Event",
    ctaType: "category",
    ctaValue: "sarees",
    isDemo: true
  },
  {
    id: "demo_banner_3",
    image: "",
    tag: "Just In",
    title: "New Products Added",
    subtitle: "Be the first to grab our latest arrivals across every category.",
    ctaText: "View New Arrivals",
    ctaType: "new",
    ctaValue: "",
    isDemo: true
  }
];
