// ============================================================
//  N&N CLOTHIFY — Product Data
//
//  This file is your store's product list.
//  DO NOT edit this file by hand — use admin.html to manage
//  products, then click "Export & Download" to get this file,
//  and commit it to GitHub.
//
//  Image field: paste the Google Drive SHARING link in admin.
//  The admin panel auto-extracts the file ID.
//
//  Name format for Google Drive files (optional shortcut):
//    "Blue Kurta_799.jpg" → name=Blue Kurta, price=₹799
// ============================================================

const PRODUCTS_DATA = [
  // ---- Demo products (replace with your real products via admin.html) ----
  {
    id: "demo_1",
    name: "Elegant Floral Kurta",
    price: 799,
    mrp: 1299,
    category: "kurtis",
    driveFileId: "",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Beautiful floral print kurta in soft breathable cotton. Perfect for casual and semi-formal occasions.",
    badge: "New",
    isDemo: true,
    demoColor: "#F5E6D3"
  },
  {
    id: "demo_2",
    name: "Banarasi Silk Saree",
    price: 2499,
    mrp: 3999,
    category: "sarees",
    driveFileId: "",
    sizes: ["Free Size"],
    description: "Gorgeous Banarasi silk saree with traditional zari work. Includes matching blouse piece.",
    badge: "Popular",
    isDemo: true,
    demoColor: "#E8D5F0"
  },
  {
    id: "demo_3",
    name: "Casual Printed Top",
    price: 499,
    mrp: 799,
    category: "tops",
    driveFileId: "",
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Trendy printed top perfect for everyday wear. Soft fabric, relaxed fit.",
    badge: "Sale",
    isDemo: true,
    demoColor: "#D5E8F0"
  },
  {
    id: "demo_4",
    name: "Flared Palazzo Pants",
    price: 699,
    mrp: 1099,
    category: "bottoms",
    driveFileId: "",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Comfortable flared palazzo pants in premium fabric. Pairs perfectly with kurtis and tops.",
    badge: "",
    isDemo: true,
    demoColor: "#D5F0E8"
  },
  {
    id: "demo_5",
    name: "Western Bodycon Dress",
    price: 1299,
    mrp: 1999,
    category: "western",
    driveFileId: "",
    sizes: ["XS", "S", "M", "L"],
    description: "Stylish bodycon dress for parties and evenings out. Stretchy, comfortable material.",
    badge: "New",
    isDemo: true,
    demoColor: "#F0D5D5"
  },
  {
    id: "demo_6",
    name: "Men's Linen Shirt",
    price: 899,
    mrp: 1499,
    category: "mens",
    driveFileId: "",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Breathable linen shirt for men. Great for both casual and formal occasions.",
    badge: "",
    isDemo: true,
    demoColor: "#E8EBD5"
  },
  {
    id: "demo_7",
    name: "Kids Ethnic Festive Set",
    price: 599,
    mrp: 999,
    category: "kids",
    driveFileId: "",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y"],
    description: "Adorable ethnic set for kids. Great for festivals, weddings, and special occasions.",
    badge: "Popular",
    isDemo: true,
    demoColor: "#F0EBD5"
  },
  {
    id: "demo_8",
    name: "Embroidered Kurti Set",
    price: 1199,
    mrp: 1799,
    category: "kurtis",
    driveFileId: "",
    sizes: ["S", "M", "L", "XL"],
    description: "Stunning embroidered kurti with matching pants. Perfect for festive occasions.",
    badge: "Festive",
    isDemo: true,
    demoColor: "#EBD5F0"
  }
];
